### ISSUE TITLE
Bug in icon sizes

### ISSUE THREAD

**Issue by GGorAA** [elrumo/macOS_Big_Sur_icons_replacements#377]
I have installed your icons to installed apps, but they are different in size. For example, as you see in that picture, IntelliJ, PyCharm, and DataGrip icons are bigger than for e. g. GitHub Desktop's icon. How can I fix this issue?

![](https://user-images.githubusercontent.com/61655029/91016152-044b1880-e5f5-11ea-898a-2a394143eaeb.png)

**Comment by elrumo** [comment]
Thanks for letting me know, should be fixed now.

**Comment by elrumo** [comment]
Not the website, but the icon files the website downloads

**Comment by GGorAA** [comment]
Thanks! I will update the icons now and test

**Comment by GGorAA** [comment]
Nope, still not the same sizes

![image](https://user-images.githubusercontent.com/61655029/91041748-3a9a8f00-e619-11ea-8513-d30da116cc76.png)
